---
title: "Retornos de ações - PETROBRAS"
output: html_document
date: "2025-14-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
# Pacotes necessários
library(quantmod) 
library(moments)
```

## Prices vs. Returns

```{r}
# Getting PBR data from August 10th 2000 to August 10th 2015.
getSymbols("PBR",from='2000-08-10',to='2015-08-10',warnings=FALSE,auto.assign=TRUE)    

n   = nrow(PBR)
pbr = as.numeric(PBR[,6])      
y   = diff(log(pbr))           
ind = trunc(seq(1,n,length=6))
date = c("Ago-00","Ago-03","Ago-06","Ago-09","Ago-12","Ago-15")

par(mfrow=c(1,2))
plot(pbr,xlab="Dias",ylab="Preço",axes=FALSE,type="l")
axis(2);axis(1,at=ind,lab=date);box()

plot(y,xlab="Dias",ylab="Retorno",axes=FALSE,type="l")
axis(2);axis(1,at=ind,lab=date);box()
```

### Autocorrelation funtion (ACF)

```{r}
par(mfrow=c(1,2))
acf(pbr,lag.max=35,main="Preço")
acf(y,lag.max=35,main="Retorno")
```

### Partial autocorrelation funtion (PACF)

```{r}
par(mfrow=c(1,2))
pacf(pbr,lag.max=35,main="Preço")
pacf(y,lag.max=35,main="Retorno")
```

## Unconditional distribution

```{r}
# normal curve
x_values <- seq(min(y), max(y), length = 10000)
mean_data <- mean(y)
sd_data <- sd(y)
normal_curve_density <- dnorm(x_values, mean = mean_data, sd = sd_data)

# Check for normality
par(mfrow=c(1,2))
hist(y,prob=TRUE,breaks=50)
lines(x_values, normal_curve_density, col = "red", lwd = 2)

qqnorm(y)
qqline(y, col = "red", lwd = 2)
```

## Summary statistics

```{r}
sum_stat = cbind(
  c("Média","Mediana","Mínimo","Máximo","Desvio padrão","Assimetria","Excesso de curtose"),
  c(mean(y),median(y),min(y),max(y),sd(y),skewness(y),kurtosis(y))
  )
sum_stat
```

## Squared returns

```{r}
plot(y^2,xlab="Dias",ylab="Quadrado do log-retorno",axes=FALSE,type="l")
axis(2);axis(1,at=ind,lab=date);box()
```

### Autocorrelation function (ACF)

```{r}
acf(y^2,lag.max=35,main="")
```

### Partial autocorrelation function (PACF)

```{r}
pacf(y^2,lag.max=35,main="")
```
