---
title: "ARIMA - retornos de ações"
output: html_document
date: "2025-10-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
# Pacotes necessários
library(tidyverse);library(quantmod);library(tseries);
library(timeSeries);library(forecast);library(xts);
options(warn=-1)
```

```{r cars}
# Importando série temporal
getSymbols('TECHM.NS', from='2012-01-01', to='2015-01-01')

# Mantendo apenas preço de fechamento
stock_prices = TECHM.NS[,4]
plot(stock_prices)
```
```{r}
# Aplicando log
stock = diff(log(stock_prices),lag=1)
stock = stock[!is.na(stock)]

# Plottando 
plot(stock,type='l', main='log returns plot')
```

```{r}
# Teste ADF
print(adf.test(stock))
```

```{r}
# Split teste/treino
breakpoint = floor(nrow(stock)*(2.9/3))
```

```{r}
# Aplicando ACF e PACF
par(mfrow = c(1,1))
acf.stock = acf(stock[c(1:breakpoint),], main='ACF Plot', lag.max=100)
pacf.stock = pacf(stock[c(1:breakpoint),], main='PACF Plot', lag.max=100)
```

```{r}
# "Gabarito" do teste
Actual_series = xts(0,as.Date("2014-11-25","%Y-%m-%d"))
 
# Dataframe de previsões
forecasted_series = data.frame(Forecasted = numeric())

for (b in breakpoint:(nrow(stock)-1)) {
  
  stock_train = stock[1:b, ]
  stock_test = stock[(b+1):nrow(stock), ]
  
  # Modelo ARIMA usando pacote forecast
  fit = Arima(stock_train, order = c(2, 0, 2), include.mean = FALSE)
  summary(fit)
  
  # Plot de resíduos ACF
  acf(fit$residuals, main = "Residuals plot")
  
  # Previsão
  arima.forecast = forecast(fit, h = 1, level = 99)
  summary(arima.forecast)
  
  # Plot das previsões
  par(mfrow = c(1,1))
  plot(arima.forecast, main = "ARIMA Forecast")
  
  # Atualiza coluna de previsão
  forecasted_series = rbind(forecasted_series, arima.forecast$mean[1])
  colnames(forecasted_series) = c("Forecasted")
  
  # Atualiza coluna de gabarito
  Actual_return = stock[(b+1), ]
  Actual_series = c(Actual_series, xts(Actual_return))
  rm(Actual_return)
}
```


```{r}
# Ajuste na série correta
Actual_series = Actual_series[-1]

# Criando objeto time series para as previsões
forecasted_series = xts(forecasted_series,index(Actual_series))

# Plot - Real versus Previsão
plot(Actual_series,type='l',main='Actual Returns Vs Forecasted Returns')
lines(forecasted_series,lwd=1.5,col='red')
legend('bottomright',c("Actual","Forecasted"),lty=c(1,1),lwd=c(1.5,1.5),col=c('black','red'))
```