---
title: "SARIMA"
output: html_document
date: "2025-10-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
# Pacotes necessários
library(forecast) 
```

```{r}
par(mfrow=c(2,4))
plot(AirPassengers)
plot(diff(AirPassengers),ylab="Diff 1",main=expression(y[t]-y[t-1]))
plot(diff(AirPassengers,12),ylab="Diff 12",main=expression(y[t]-y[t-12]))
plot(diff(diff(AirPassengers,1),12),ylab="Diff 1,12",main=expression(y[t]-y[t-1]-y[t-12]+y[t-13]))

plot(log(AirPassengers))
plot(diff(log(AirPassengers)),ylab="Diff 1",main=expression(y[t]-y[t-1]))
plot(diff(log(AirPassengers),12),ylab="Diff 12",main=expression(y[t]-y[t-12]))
plot(diff(diff(log(AirPassengers),1),12),ylab="Diff 1,12",main=expression(y[t]-y[t-1]-y[t-12]+y[t-13]))
```

## Linear trend and dummies for months

```{r}
n  <- length(AirPassengers)
n1 <- 108 #Test sample
month_ind <- kronecker(matrix(1,n/12,1),rbind(diag(1,11),rep(0,11)))
lin_trend <- 1:n
X <- cbind(1,lin_trend,month_ind)
```

## Deterministic seasonality - AirPassengers and log-AirPassengers

```{r}
reg1 = lm(AirPassengers[1:n1]~X[1:n1,]-1)
fit1 = ts(reg1$fit,start=c(1949,1),end=c(1957,12),frequency=12)

reg2 = lm(log(AirPassengers[1:n1])~X[1:n1,]-1)
fit2 = ts(reg2$fit,start=c(1949,1),end=c(1957,12),frequency=12)
```

## Seasonal ARIMA modeling of AirPassengers

### Calculate the BIC under different specifications

```{r}
bics = matrix(0,16,5)
s = 0
for (i in 0:1)
  for (j in 0:1)
    for (k in 0:1)
      for (l in 0:1){
        s = s + 1
        bics[s,] = c(i,j,k,l,Arima(window(AirPassengers,end=1957+11/12), 
                     order=c(i,1,j),seasonal=list(order=c(k,1,l),period=12),
                     lambda=0)$bic)
      }
bics[bics[,5]==min(bics[,5]),]
```

### Fit the best model

```{r}
air.model = Arima(window(AirPassengers,end=1957+11/12), order=c(0,1,1),
                  seasonal=list(order=c(0,1,1),period=12), lambda=0) 
sarima1 = air.model
air.model
```

## Compare deterministic seasonality and seasonal ARIMA

```{r}
par(mfrow=c(1,3))

plot(AirPassengers,ylim=range(AirPassengers,fit1))
lines(fit1,col=2)
legend("topleft",legend=c("Data","Fit"),col=1:2,lty=1)
title("Deterministic cycle")

plot(log(AirPassengers),ylim=range(log(AirPassengers),fit2))
lines(fit2,col=2)
legend("topleft",legend=c("Data","Fit"),col=1:2,lty=1)
title("Deterministic cycle")

plot(AirPassengers,ylim=range(AirPassengers,air.model$fit))
lines(air.model$fit,col=2)
legend("topleft",legend=c("Data","Fit"),col=1:2,lty=1)
title("ARIMA(0,1,1)(0,1,1)[12]")
sarima1 = air.model
```

## Forecast exercise

```{r}
par(mfrow=c(1,3))

# Deterministic seasonality - AirPassengers
fit11 = ts(X[(n1+1):n,]%*%reg1$coef,start=c(1958,1),end=c(1960,12),frequency=12)
plot(AirPassengers,ylim=range(AirPassengers,fit1))
lines(fit1,col=2)
lines(fit11,col=4)
title("Deterministic cycle")

# Deterministic seasonality - log-AirPassengers
fit21 = ts(X[(n1+1):n,]%*%reg2$coef,start=c(1958,1),end=c(1960,12),frequency=12)
plot(log(AirPassengers),ylim=range(log(AirPassengers),fit2,fit21))
lines(fit2,col=2)
lines(fit21,col=4)
title("Deterministic cycle")

# Seasonal ARIMA
air.model = Arima(window(AirPassengers,end=1957+11/12), order=c(0,1,1),
                  seasonal=list(order=c(0,1,1),period=12), lambda=0) 
plot(forecast(air.model,h=36),ylab="AirPassengers")
lines(AirPassengers)
sarima2 = air.model
```
